name: catalogo_reinstreet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.3
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  min_sdk_android: 21 # android min sdk min:16, default 21


